Imrpoved text, commands and the way the bot handle rates
CaioCS97/dolinho-bot pull request #6
Opened 2023-10-28 19:29 UTC by joaoscheuermann

2023-10-28 22:46 UTC, CaioCS97 commented on package.json
> +    "@types/sinon": "^10.0.20",
I think this is not being used

2023-10-28 23:20 UTC, CaioCS97 requested changes

2023-10-28 23:20 UTC, CaioCS97 commented on src/index.ts
> +// Initializes the market with the corretc rates
typo

2023-10-28 23:20 UTC, CaioCS97 commented on src/market/index.ts
> +    // so we can calculate the variation and percentage on the first update without getting crazy and irrealistc values.
typo 
```suggestion
    // so we can calculate the variation and percentage on the first update without getting crazy and unrealistic values.
```

2023-10-28 23:20 UTC, CaioCS97 commented on src/utils/__tests__/calculateVariation.spec.ts
> +    // @ts-ignore
why are these ignores necessary?

2023-10-28 23:20 UTC, CaioCS97 commented
Nice changes!

2023-10-29 21:50 UTC, joaoscheuermann commented on package.json
> +    "@types/sinon": "^10.0.20",
Done

2023-10-29 21:53 UTC, joaoscheuermann commented on src/discord/commands/usd.ts
> +    .setDescription("Replies with Pong!"),
Done

2023-10-29 21:57 UTC, joaoscheuermann commented on src/index.ts
> +// Initializes the market with the corretc rates
fixed

2023-10-29 21:58 UTC, joaoscheuermann commented on src/utils/__tests__/calculateVariation.spec.ts
> +    // @ts-ignore
Dunno :c chat gpt created it

2023-10-29 22:01 UTC, joaoscheuermann commented on src/market/index.ts
> +    // so we can calculate the variation and percentage on the first update without getting crazy and irrealistc values.
Fixed

2023-10-29 22:57 UTC, CaioCS97 approved these changes

2023-10-29 22:57 UTC, merged